-- DO NOT EDIT THIS FILE, GENERATED BY LUAPB-SAVEAST 
local _, MySlot = ...

local t = {
-- Table: {1}
{
   ["types"]={2},
},
-- Table: {2}
{
   {3},
   {4},
   {5},
   {6},
   {7},
   {8},
   {9},
   ["Inventory"]={4},
   ["Bag"]={5},
   ["Bind"]={8},
   ["Slot"]={6},
   ["Macro"]={7},
   ["Charactor"]={3},
   ["Key"]={9},
},
-- Table: {3}
{
   ["fields"]={10},
   ["name"]="Charactor",
   [".type"]="message",
},
-- Table: {4}
{
   ["fields"]={11},
   ["name"]="Inventory",
   [".type"]="message",
},
-- Table: {5}
{
   ["fields"]={12},
   ["name"]="Bag",
   [".type"]="message",
},
-- Table: {6}
{
   ["fields"]={13},
   ["name"]="Slot",
   [".type"]="message",
   ["types"]={14},
},
-- Table: {7}
{
   ["fields"]={15},
   ["name"]="Macro",
   [".type"]="message",
},
-- Table: {8}
{
   ["fields"]={16},
   ["name"]="Bind",
   [".type"]="message",
},
-- Table: {9}
{
   ["fields"]={17},
   ["name"]="Key",
   [".type"]="message",
},
-- Table: {10}
{
   {18},
   {19},
   {20},
   {21},
   {22},
   {23},
   {24},
   {25},
   {26},
   {27},
   {28},
   {29},
   ["inventory"]={28},
   ["bag"]={29},
   ["name"]={22},
   ["slot"]={18},
   ["macro"]={20},
   ["class"]={25},
   ["ver"]={21},
   ["race"]={24},
   ["bind"]={19},
   ["sex"]={26},
   ["level"]={27},
   ["realm"]={23},
},
-- Table: {11}
{
   {30},
   {31},
   ["itemLink"]={31},
   ["id"]={30},
},
-- Table: {12}
{
   {32},
   {33},
   {34},
   ["id"]={32},
   ["item"]={34},
   ["baglink"]={33},
},
-- Table: {13}
{
   {35},
   {36},
   {37},
   {38},
   ["id"]={35},
   ["type"]={36},
   ["index"]={37},
   ["strindex"]={38},
},
-- Table: {14}
{
   {39},
   ["SlotType"]={39},
},
-- Table: {15}
{
   {40},
   {41},
   {42},
   {43},
   ["id"]={42},
   ["icon"]={43},
   ["name"]={40},
   ["body"]={41},
},
-- Table: {16}
{
   {44},
   {45},
   {46},
   {47},
   ["command"]={47},
   ["key1"]={45},
   ["id"]={44},
   ["key2"]={46},
},
-- Table: {17}
{
   {48},
   {49},
   {50},
   ["mod"]={49},
   ["key"]={48},
   ["keycode"]={50},
},
-- Table: {18}
{
   ["ftype"]="Slot",
   ["name"]="slot",
   [".type"]="field",
   ["rule"]="repeated",
   ["tag"]=1,
},
-- Table: {19}
{
   ["ftype"]="Bind",
   ["name"]="bind",
   [".type"]="field",
   ["rule"]="repeated",
   ["tag"]=2,
},
-- Table: {20}
{
   ["ftype"]="Macro",
   ["name"]="macro",
   [".type"]="field",
   ["rule"]="repeated",
   ["tag"]=3,
},
-- Table: {21}
{
   ["ftype"]="uint32",
   ["name"]="ver",
   [".type"]="field",
   ["rule"]="optional",
   ["tag"]=14,
},
-- Table: {22}
{
   ["ftype"]="string",
   ["name"]="name",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=15,
},
-- Table: {23}
{
   ["ftype"]="string",
   ["name"]="realm",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=16,
},
-- Table: {24}
{
   ["ftype"]="int32",
   ["name"]="race",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=17,
},
-- Table: {25}
{
   ["ftype"]="int32",
   ["name"]="class",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=18,
},
-- Table: {26}
{
   ["ftype"]="int32",
   ["name"]="sex",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=19,
},
-- Table: {27}
{
   ["ftype"]="int32",
   ["name"]="level",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=20,
},
-- Table: {28}
{
   ["ftype"]="Inventory",
   ["name"]="inventory",
   [".type"]="field",
   ["rule"]="repeated",
   ["tag"]=21,
},
-- Table: {29}
{
   ["ftype"]="Bag",
   ["name"]="bag",
   [".type"]="field",
   ["rule"]="repeated",
   ["tag"]=22,
},
-- Table: {30}
{
   ["ftype"]="int32",
   ["name"]="id",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=1,
},
-- Table: {31}
{
   ["ftype"]="string",
   ["name"]="itemLink",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=2,
},
-- Table: {32}
{
   ["ftype"]="int32",
   ["name"]="id",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=1,
},
-- Table: {33}
{
   ["ftype"]="string",
   ["name"]="baglink",
   [".type"]="field",
   ["rule"]="optional",
   ["tag"]=2,
},
-- Table: {34}
{
   ["ftype"]="string",
   ["name"]="item",
   [".type"]="field",
   ["rule"]="repeated",
   ["tag"]=3,
},
-- Table: {35}
{
   ["ftype"]="uint32",
   ["name"]="id",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=1,
},
-- Table: {36}
{
   ["ftype"]="SlotType",
   ["name"]="type",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=2,
},
-- Table: {37}
{
   ["ftype"]="uint32",
   ["name"]="index",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=3,
},
-- Table: {38}
{
   ["ftype"]="string",
   ["name"]="strindex",
   [".type"]="field",
   ["rule"]="optional",
   ["tag"]=4,
},
-- Table: {39}
{
   [".type"]="enum",
   ["name"]="SlotType",
   ["values"]={51},
},
-- Table: {40}
{
   ["ftype"]="string",
   ["name"]="name",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=1,
},
-- Table: {41}
{
   ["ftype"]="string",
   ["name"]="body",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=2,
},
-- Table: {42}
{
   ["ftype"]="uint32",
   ["name"]="id",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=3,
},
-- Table: {43}
{
   ["ftype"]="string",
   ["name"]="icon",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=4,
},
-- Table: {44}
{
   ["ftype"]="uint32",
   ["name"]="id",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=1,
},
-- Table: {45}
{
   ["ftype"]="Key",
   ["name"]="key1",
   [".type"]="field",
   ["rule"]="optional",
   ["tag"]=2,
},
-- Table: {46}
{
   ["ftype"]="Key",
   ["name"]="key2",
   [".type"]="field",
   ["rule"]="optional",
   ["tag"]=3,
},
-- Table: {47}
{
   ["ftype"]="string",
   ["name"]="command",
   [".type"]="field",
   ["rule"]="optional",
   ["tag"]=15,
},
-- Table: {48}
{
   ["ftype"]="uint32",
   ["name"]="key",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=1,
},
-- Table: {49}
{
   ["ftype"]="uint32",
   ["name"]="mod",
   [".type"]="field",
   ["rule"]="required",
   ["tag"]=2,
},
-- Table: {50}
{
   ["ftype"]="string",
   ["name"]="keycode",
   [".type"]="field",
   ["rule"]="optional",
   ["tag"]=15,
},
-- Table: {51}
{
   "SPELL",
   "ITEM",
   "MACRO",
   "FLYOUT",
   "EMPTY",
   "EQUIPMENTSET",
   "SUMMONPET",
   "COMPANION",
   "SUMMONMOUNT",
   ["EMPTY"]=5,
   ["FLYOUT"]=4,
   ["SPELL"]=1,
   ["ITEM"]=2,
   ["SUMMONMOUNT"]=9,
   ["SUMMONPET"]=7,
   ["MACRO"]=3,
   ["COMPANION"]=8,
   ["EQUIPMENTSET"]=6,
},
}
   local function loadast()
      local tables = t 
      for idx = 1,#tables do
	 local tolinki = {}
	 for i,v in pairs( tables[idx] ) do
	    if type( v ) == "table" then
	       tables[idx][i] = tables[v[1]]
	    end
	    if type( i ) == "table" and tables[i[1]] then
	       table.insert( tolinki,{ i,tables[i[1]] } )
	    end
	 end
	 -- link indices
	 for _,v in ipairs( tolinki ) do
	    tables[idx][v[2]],tables[idx][v[1]] =  tables[idx][v[1]],nil
	 end
      end
      return tables[1]
   end
 
MySlot.ast = loadast()
